version: '3'

services:
  nats-server:
    image: nats:2.10.25-alpine3.21
    ports:
      - "8222:8222"
      - "4222:4222"

  client-gateway:
    build: ./client-gateway
    ports:
      - "3001:3001"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
  
  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db


  # postgres-orders-ms-db:
  #   container_name: postgresdb-orders-ms
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=12345
  #     - POSTGRES_DATABASE=ordersdb
  #   volumes:
  #     - ./orders-ms/postgres:/var/lib/postgresql/data

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile
    ports:
      - 3002:3002
    # depends_on: 
    #   - postgres-orders-ms-db
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://ordersms_owner:npg_A1eFnjMzsOc5@ep-snowy-cloud-a8a294mu-pooler.eastus2.azure.neon.tech/ordersms?sslmode=require

  payment-ms:
    build: ./payment-ms
    ports:
      - 3003:3003
    command: npm run start:dev
    env_file: ./payment-ms/.env
    environment:
      - PORT=3003
      - API_KEY_STRIPE=${API_KEY_STRIPE}
      - CANCEL_URL=${CANCEL_URL}
      - SUCCESS_URL=${SUCCESS_URL}
      - SECRET_ENDPOINT_WEBHOOK_KEY=${SECRET_ENDPOINT_STRIPE_WEBHOOK_KEY}
      - NATS_SERVERS=nats://nats-server:4222
    volumes:
      - ./payment-ms/src:/usr/src/app/src
    
  auth-ms:
    build: ./auth-ms
    ports:
      - 3000:3000
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MS_MONGO_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./auth-ms/src:/usr/src/app/src